FORMAT: 1A
HOST: https://www.livingroomofsatoshi.com/api/v1

# Living Room of Satoshi API
Pay any Australian bill or bank account with bitcoin using our API.

**HTTP Basic Auth** is required for all endpoints. 

Request an API username and password at support@livingroomofsatoshi.com

# Group Rates
Australian Bitcoin Exchange rate, updated every 30 seconds.

## Current Rate [/current_rate]

### Retrieve Current rate [GET]
+ Response 200 (application/json)

        {"amount":525.67,"currency":"AUD"}

        
# Group Bitcoin Bank Transfer
Pay bitcoin to any Australian Bank Account (even your own!) using Direct Bank Transfer details (BSB and Account number).

The POST response will contain a *bitcoin_payment_address* and *bitcoin_payment_amount*, which you can make payment to. Payment must be made within 15 minutes, to ensure that the current exchange rate is used.

The bank transfer's status will be updated to PAID when your bitcoin payment is received.

If payment happens before 5pm Australian Eastern Standard time, funds will generally arrive in the bank account within 2 business days, depending on the bank.


|Parameter name|Used in |Description|
|:-------------|:-------|:-------------|
| amount      |POST, GET| Australian Dollar Amount (numeric) |
| bsb       |POST, GET| Bank BSB (numeric)      |
| account_number |POST, GET| Bank Account Number (numeric)      |
| description |POST, GET| This will appear on the payee's bank statement (String, max 18 characters, optional)      |
| email |POST,GET| A comma separated list of email addresses to send payment confirmation receipts to. e.g. "one@example.com" or "one@example.com,two@example.com" <br/> (String, optional)|
| id |GET| unique id of the bill (numeric)      |
| status |GET| Bill Status (UNPAID, PAID, ERROR)      |
|bitcoin_payment_address|GET|Bitcoin address to make payment to|
|bitcoin_payment_amount|GET|Bitcoin amount to pay (numeric). Must be paid immediately after bill is created or refreshed. <br>Bill can be refreshed by simply doing a GET on the existing bill. <br>If the bill status is PAID, this field will show the actual bitcoin amount paid.|

## Bank Transfers [/bills/bank_transfer]

### Create a Bank Transfer [POST]

+ Request (application/json)

        { 
          "amount":246.40, 
          "bsb":244400,
          "account_number":460808934,
          "description":"For Invoice 12345"
        }

+ Response 201 (application/json)

        {
          "id":3,
          "amount":246.40,
          "bsb":"244400",
          "account_number":"460808934",
          "description":"For Invoice 12345",
          "status":"UNPAID",
          "email":"",
          "bitcoin_payment_address":"1AaxRWDPRbxXvYfFCjwNw4zQSf2tBXj9UA",
          "bitcoin_payment_amount":0.49295
        }

+ Response 400 (application/json)
        
        [{"field":"bsb","message":"Not a valid Australian BSB."}]


### List all Bank Transfers [GET]
+ Response 200 (application/json)

        [{
          "id":3,
          "amount":246.40,
          "bsb":"244400",
          "account_number":"460808934",
          "description":"For Invoice 12345",
          "status":"UNPAID",
          "email":"",
          "bitcoin_payment_address":"1AaxRWDPRbxXvYfFCjwNw4zQSf2tBXj9UA",
          "bitcoin_payment_amount":0.49295
        },{
          "id":4,
          "amount":1220.00,
          "bsb":"306460",
          "account_number":"944733829",
          "description":"",
          "status":"PAID",
          "email":"one@example.com,two@example.com",
          "bitcoin_payment_address":"1JkftJEc5ZBAJH8aZch5FUgNq3H87oe9tw",
          "bitcoin_payment_amount":2.88871
        }]

     
## Bank Transfer [/bills/bank_transfer/{id}]

+ Parameters
    + id (required, number) ... Numeric `id` of the Bank Transfer

### Retrieve a single Bank Transfer [GET]
+ Response 200 (application/json)

        {
          "id":3,
          "amount":246.40,
          "bsb":"244400",
          "ref":"460808934",
          "description":"For Invoice 12345",
          "status":"UNPAID",
          "email":"",
          "bitcoin_payment_address":"1AaxRWDPRbxXvYfFCjwNw4zQSf2tBXj9UA",
          "bitcoin_payment_amount":0.49295
        }
                
# Group Bitcoin BPAY Bills
Pay any BPAY bill with bitcoin by POSTing to the endpoint below. 

The POST response will contain a *bitcoin_payment_address* and *bitcoin_payment_amount* for you to make payment to. Payment must be made within 15 minutes, to ensure that the current exchange rate is used. 

The bill's status will be updated to PAID when your bitcoin payment is received. 

If you submit your payment before 5pm on a Bank Business Day, the biller will acknowledge the payment as having been made on that day and should process the payment on the next banking business day. If you submit a payment on a weekend or public holiday or you missed the 5pm cutoff time, the biller will receive the payment within 2 banking business days.

|Parameter name|Used in |Description|
|:-------------|:-------|:-------------|
| amount      |POST, GET| Australian Dollar Amount (numeric) |
| biller       |POST, GET| BPAY biller code (numeric)      |
| ref |POST, GET| BPAY Reference number (numeric)      |
| email |POST,GET| A comma separated list of email addresses to send payment confirmation receipts to. e.g. "one@example.com" or "one@example.com,two@example.com" <br/> (String, optional)|
| id |GET| unique id of the bill (numeric)      |
| status |GET| Bill Status (UNPAID, PAID, ERROR)      |
|bitcoin_payment_address|GET|Bitcoin address to make payment to|
|bitcoin_payment_amount|GET|Bitcoin amount to pay (numeric). Must be paid immediately after bill is created or refreshed. <br>Bill can be refreshed by simply doing a GET on the existing bill. <br>If the bill status is PAID, this field will show the actual bitcoin amount paid.|

## BPAY Bills [/bills/bpay]

### Create a BPAY Bill [POST]

+ Request (application/json)

        { 
          "amount":123.45, 
          "biller":"23796",
          "ref":"1000023451"
        }

+ Response 201 (application/json)

        {
          "id":1,
          "amount":123.45,
          "biller":"23796",
          "ref":"1000023451",
          "status":"UNPAID",
          "email":"",
          "bitcoin_payment_address":"1AaxRWDPRbxXvYfFCjwNw4zQSf2tBXj9UA",
          "bitcoin_payment_amount":0.23723
        }

+ Response 400 (application/json)
        
        [{"field":"biller","message":"Biller is unknown."}]


### List all BPAY Bills [GET]
+ Response 200 (application/json)

        [{
          "id":1,
          "amount":123.45,
          "biller":"23796",
          "ref":"1000023451",
          "status":"UNPAID",
          "email":"",
          "bitcoin_payment_address":"1AaxRWDPRbxXvYfFCjwNw4zQSf2tBXj9UA",
          "bitcoin_payment_amount":0.23723
        },{
          "id":2,
          "amount":2330.00,
          "biller":"1818",
          "ref":"3999229",
          "status":"PAID",
          "email":"one@example.com,two@example.com",
          "bitcoin_payment_address":"1JkftJEc5ZBAJH8aZch5FUgNq3H87oe9tw",
          "bitcoin_payment_amount":4.99871
        }]

     
## BPAY Bill [/bills/bpay/{id}]

+ Parameters
    + id (required, number) ... Numeric `id` of the Bill

### Retrieve a single BPAY Bill [GET]
+ Response 200 (application/json)

        {
          "id":1,
          "amount":123.45,
          "biller":"23796",
          "ref":"1000023451",
          "status":"UNPAID",
          "email":"",
          "bitcoin_payment_address":"1AaxRWDPRbxXvYfFCjwNw4zQSf2tBXj9UA",
          "bitcoin_payment_amount":0.23723
        }

# Group BSB
BSB data, useful for display or validation.

## BSB [/bsb/{bsb}]

Supplied BSB numbers will be accepted by all endpoints on this API in any of these formats: "638001", "638-001", "638 001".

It can also be used to validate BSB numbers, returning a 404 if it is invalid.

We recommend always stripping spaces though, just to avoid any possible HTTP weirdness. 

### Retrieve BSB Data [GET]
+ Response 200 (application/json)

        {"bsb":"638001","mnemonic":"HBS","bank_name":"Heritage Bank Limited"}

+ Response 404 (application/json)